services:
  ffvn-4k-api:
    build: .
    container_name: ffvn-4k-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./storage:/app/storage
      - ./public/fonts:/app/public/fonts:ro